HearthDuster/HearthDuster/HearthDuster/HearthDuster.Web/Areas/Administrator/Controllers/CardController.cs
using HearthDuster.DataAccess;
using HearthDuster.Domain;
using HearthDuster.Domain.Enums;
using HearthDuster.Web.Areas.Administrator.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HearthDuster.Web.Helpers;
using System.Net;

namespace HearthDuster.Web.Areas.Administrator.Controllers
{
    [Authorize(Roles ="Administrator")]
    public class CardController : Controller
    {
        hearthdusterdbEntities _db = new hearthdusterdbEntities();

        // GET: Administrator/Card
        [HttpGet]
        public ActionResult Index(string SearchString = "", int page = 1)
        {
            dynamic model = new ExpandoObject();

            const int pageSize = 8;

            var cards = _db.Cards.ToList();

            IEnumerable<Cards> ieCards = cards;

            var pagedCards = new PaginatedList<Cards>(ieCards, page, pageSize);

            model.Cards = pagedCards;

            var images = new List<Files>();

            if(!String.IsNullOrEmpty(SearchString))
            {
                ieCards = ieCards.Where(c => c.Name.Contains(SearchString));
                ieCards.OrderBy(c => c.Name).ThenBy(c => c.Mana);

                foreach(var card in ieCards)
                {
                    if(card.Name.ToLower().Contains(SearchString.ToLower()))
                    {
                        images.Add(_db.Files.Find(card.FileId));
                    }
                }
            }
            else
            {
                ieCards.OrderBy(c => c.Name).ThenBy(c => c.Mana);

                foreach (var card in ieCards)
                {
                    images.Add(_db.Files.Find(card.FileId));
                }
            }

            var pagedImages = new PaginatedList<Files>(images, page, pageSize);

            model.Images = pagedImages;

            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            CardCreateViewModel model = new CardCreateViewModel();

            var Mechanics = _db.Mechanics.ToList();

            var MechanicsSelectList = new List<SelectListItem>();

            foreach(var mechanic in Mechanics)
            {
                MechanicsSelectList.Add(new SelectListItem { Value = mechanic.MechanicId.ToString(), Text = mechanic.Name });
            }

            model.Mechanics = MechanicsSelectList;

            return View(model);
        }

        [HttpPost]
        public ActionResult Create(CardCreateViewModel model)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    byte[] fileData = new byte[model.FileUpload.InputStream.Length];
                    model.FileUpload.InputStream.Read(fileData, 0, fileData.Length);

                    var newFile = new Domain.Files
                    {
                        UserId = User.Identity.GetUserId(),
                        FileData = fileData,
                        MimeType = model.FileUpload.ContentType,
                        OriginalFileName = model.FileUpload.FileName,
                        DateUploaded = DateTime.Now
                    };

                    var newCard = new Domain.Cards
                    {
                        Text = model.Text,
                        Attack = model.Attack,
                        Name = model.Name,
                        Rarity = Enum.GetName(typeof(Rarity), model.Rarity),
                        Type = Enum.GetName(typeof(CardType), model.Type),
                        CardSet = Enum.GetName(typeof(CardSet), model.Set),
                        Health = model.Health,
                        Mana = model.Mana,
                        FileId = newFile.FileId
                    };

                    _db.Files.Add(newFile);
                    _db.Cards.Add(newCard);
                
                    _db.SaveChanges();

                    TempData["CardCreateSuccess"] = "Card created successfully!";
                    return RedirectToAction("Create");
                }
                catch(Exception ex)
                {
                    TempData["CardCreateError"] = "Sorry there has been an error. Card not saved.";
                    return RedirectToAction("Create");
                }
                
            }
            else
            {
                return View(model);
            }
        }

        public PartialViewResult CardDetails(int id)
        {
            dynamic model = new ExpandoObject();

            var card = _db.Cards.Find(id);

            model.Card = card;
            model.Image = _db.Files.Find(card.FileId);

            return PartialView(model);
        }
    }
}

HearthDuster/HearthDuster/HearthDuster/HearthDuster.Web/Areas/Administrator/Controllers/DeckController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HearthDuster.Domain;
using HearthDuster.DataAccess;
using HearthDuster.Web.Areas.Administrator.ViewModels;
using HearthDuster.Domain.Enums;

namespace HearthDuster.Web.Areas.Administrator.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class DeckController : Controller
    {
        hearthdusterdbEntities _db = new hearthdusterdbEntities();
        // GET: Administrator/Deck
        public ActionResult Index()
        {
            var decks = _db.Decks.ToList();
            var cards = _db.Cards.ToList();

            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            DeckCreateViewModel model = new DeckCreateViewModel();

            return View(model);
        }

        [HttpPost]
        public ActionResult Create(DeckCreateViewModel model) // need to think of how to account for card quantity
        {
            if(ModelState.IsValid)
            {
                var cards = model.Cards;

                var newDeck = new Domain.Decks
                {
                    Class = model.Class.ToString(),
                    Name = model.Name,
                    Cost = model.Cost,
                    Description = model.Description,
                    Author = model.Author
                };

                _db.Decks.Add(newDeck);

                _db.SaveChanges();


                TempData["notice"] = "Deck saved successfully.";
                return RedirectToAction("Index");
            }else
            {
                return View(model);
            }
            
        }



        public ActionResult Details(Decks deck)
        {
            var cards = deck.Cards.ToList();

            return View(cards);
        }
    }
}

HearthDuster/HearthDuster/HearthDuster/HearthDuster.Web/Areas/Administrator/Views/Shared/_CardDetails.cshtml
@Model dynamic

<div id="ViewCardDetails">

</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CardId }) |
    <button type="button" class="btn btn-default" data-dissmiss="modal">Close</button>
</p>

HearthDuster/HearthDuster/HearthDuster/HearthDuster.Web/Areas/Administrator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Admin Area | HearthDuster</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Hearth Duster", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @*@if (User.IsInRole("Administrator")) // DEPRICATED: need to create html helper method and authorize in controller see: http://stackoverflow.com/questions/25772851/asp-net-mvc-4-custom-role-authorization-show-hide-edit-delete-links-in-views
                { ADMIN ROLE NOT WORKING RIGHT NOW
                    @Html.ActionLink("Admin Area", "Index", "Home", new { @class = "alert-link" })
                }*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Admin Area", "Index", "Home", new { @class = "alert-link" })</li>
                </ul>
                <div class="dropdown">
                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown" style="align-self:center">Management<span class="caret"></span></button>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Cards", "Index", "Card")</li>
                        <li>@Html.ActionLink("Decks", "Index", "Deck")</li>
                        <li>@Html.ActionLink("Comments", null, null, new { Href = "#" })</li> @* TO DO: Implement these other admin areas. *@
                        <li>@Html.ActionLink("Users", null, null, new { Href = "#" })</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - HearthDuster</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>